DROP TABLE IF EXISTS EMP_DATA;

CREATE TABLE EMP_DATA
(
    id  INT AUTO_INCREMENT  PRIMARY KEY,
    name_emp VARCHAR(250) NOT NULL ,
    type_emp VARCHAR(250) NOT NULL ,
    FTI_info INT(250) DEFAULT NOT NULL
);
